### PR TITLE
Move license file to root folder and rename it

### PR DESCRIPTION
**Pull request by Danghor**
This way people can find it quicker and I also think the license will then show up at the top bar in GitHub

### CODE REVIEW

**Review by Wumpf — CHANGES_REQUESTED** [review]
The license file is included in the VSIX. You haven't changed the project file to reflect that. Please make sure that the license text shows up when installing the VSIX.
See https://github.com/Wumpf/VSSolutionColor/blob/master/SolutionColor/SolutionColor.csproj#L80

**Comment by Danghor** [comment]
I tried to test whether everything worked correctly, however I am unable to build this project, since I always get the error `The specified task executable location "[...]\VSSolutionColor\packages\Microsoft.VSSDK.BuildTools.14.3.25407\tools\VSSDK\bin\VsixUtil.exe" is invalid.`

May I ask what Visual Studio version you use to build?

**Comment by Wumpf** [comment]
I think I used vs2017 last time around. That error might imply that you don't have the VS extension tools installed

**Comment by Danghor** [comment]
I updated the project file and the vsixmanifest. Now the License will show up when starting the VSIX installer 😊

**Pull request closed without merging**
